// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-dentists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var dentists = [
  {
    id: 1,
    name: "Dr. Emily Carter, DDS",
    officeName: "Bright Smile Dental",
    specialty: "General Dentist",
    rating: 4.8,
    reviews: 120,
    distance: "0.5 miles away",
    address: "123 Newark Ave, Jersey City, NJ 07302",
    insurance: ["Aetna", "Cigna", "MetLife", "Delta Dental", "United Concordia"],
    networkProvider: true,
    latitude: 40.7282,
    longitude: -74.0431
  },
  {
    id: 2,
    name: "Dr. Michael Rodriguez, DDS",
    officeName: "Hudson Family Dental",
    specialty: "Orthodontist",
    rating: 4.6,
    reviews: 89,
    distance: "1.2 miles away",
    address: "456 Summit Ave, Jersey City, NJ 07306",
    insurance: ["Aetna", "Delta Dental", "Cigna", "MetLife", "United Concordia"],
    networkProvider: false,
    latitude: 40.738,
    longitude: -74.065
  },
  {
    id: 3,
    name: "Dr. Sarah Kim, DDS",
    officeName: "Grand Street Dental Care",
    specialty: "Cosmetic Dentist",
    rating: 4.9,
    reviews: 156,
    distance: "0.8 miles away",
    address: "789 Grand St, Jersey City, NJ 07302",
    insurance: ["Aetna", "MetLife", "Cigna", "Delta Dental", "United Concordia"],
    networkProvider: true,
    latitude: 40.7178,
    longitude: -74.049
  },
  {
    id: 4,
    name: "Dr. James Wilson, DDS",
    officeName: "Central Pediatric Dentistry",
    specialty: "Pediatric Dentist",
    rating: 4.7,
    reviews: 98,
    distance: "1.5 miles away",
    address: "321 Central Ave, Jersey City, NJ 07307",
    insurance: ["Delta Dental", "United Concordia", "Cigna", "Aetna", "MetLife"],
    networkProvider: false,
    latitude: 40.7485,
    longitude: -74.0545
  },
  {
    id: 5,
    name: "Dr. Lisa Chen, DMD",
    officeName: "Bergen Periodontal Associates",
    specialty: "Periodontist",
    rating: 4.9,
    reviews: 142,
    distance: "1.8 miles away",
    address: "567 Bergen Ave, Jersey City, NJ 07304",
    insurance: ["Aetna", "MetLife", "Cigna", "Delta Dental", "United Concordia"],
    networkProvider: true,
    latitude: 40.7089,
    longitude: -74.062
  },
  {
    id: 6,
    name: "Dr. Robert Martinez, DDS",
    officeName: "Kennedy Oral Surgery Center",
    specialty: "Oral Surgeon",
    rating: 4.8,
    reviews: 134,
    distance: "2.1 miles away",
    address: "890 Kennedy Blvd, Jersey City, NJ 07305",
    insurance: ["Delta Dental", "United Concordia", "Aetna", "Cigna", "MetLife"],
    networkProvider: false,
    latitude: 40.702,
    longitude: -74.075
  }
];
var insuranceCarriers = [
  "Aetna",
  "Blue Cross Blue Shield",
  "Cigna",
  "Delta Dental",
  "Humana",
  "MetLife",
  "United Concordia"
];
var specialties = [
  "General Practitioner",
  "Pediatric Dentist",
  "Endodontist",
  "Oral Surgeon",
  "Orthodontist",
  "Periodontist",
  "Cosmetic Dentist"
];

// src/lib/mcp/tools/search-dentists.ts
var search_dentists_default = defineTool({
  name: "search_dentists",
  title: "Search dentists",
  description: "Search the findadentist directory of dentists by specialty, accepted insurance carrier, city or address text, and minimum rating.",
  inputSchema: {
    query: z.string().optional().describe("Free text matched against dentist name, office name, or address."),
    specialty: z.string().optional().describe("Specialty such as Orthodontist, Periodontist, Pediatric Dentist."),
    insurance: z.string().optional().describe("Insurance carrier the dentist must accept, e.g. Aetna."),
    minRating: z.number().optional().describe("Minimum star rating from 0 to 5."),
    networkOnly: z.boolean().optional().describe("Only return Dental.com Network providers."),
    limit: z.number().optional().describe("Maximum number of results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, specialty, insurance, minRating, networkOnly, limit }) => {
    const q = query?.trim().toLowerCase();
    const results = dentists.filter((d) => {
      if (q && ![d.name, d.officeName, d.address].some((f) => f.toLowerCase().includes(q))) return false;
      if (specialty && !d.specialty.toLowerCase().includes(specialty.trim().toLowerCase())) return false;
      if (insurance && !d.insurance.some((i) => i.toLowerCase() === insurance.trim().toLowerCase())) return false;
      if (typeof minRating === "number" && d.rating < minRating) return false;
      if (networkOnly && !d.networkProvider) return false;
      return true;
    }).sort((a, b) => Number(b.networkProvider) - Number(a.networkProvider) || b.rating - a.rating).slice(0, Math.max(1, Math.min(limit ?? 10, 50)));
    return {
      content: [
        {
          type: "text",
          text: results.length ? results.map(
            (d) => `#${d.id} ${d.name} \u2014 ${d.officeName} (${d.specialty})
${d.address}
Rating ${d.rating} (${d.reviews} reviews), ${d.distance}
Insurance: ${d.insurance.join(", ")}${d.networkProvider ? "\nDental.com Network provider" : ""}`
          ).join("\n\n") : "No dentists matched those filters."
        }
      ],
      structuredContent: { count: results.length, dentists: results }
    };
  }
});

// src/lib/mcp/tools/get-dentist.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_dentist_default = defineTool2({
  name: "get_dentist",
  title: "Get dentist details",
  description: "Get the full profile of one dentist in the findadentist directory by id.",
  inputSchema: { id: z2.number().describe("Dentist id returned by search_dentists.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const dentist = dentists.find((d) => d.id === id);
    if (!dentist) throw new ToolError(`No dentist found with id ${id}.`);
    return {
      content: [
        {
          type: "text",
          text: `${dentist.name} \u2014 ${dentist.officeName}
Specialty: ${dentist.specialty}
Address: ${dentist.address}
Rating: ${dentist.rating} (${dentist.reviews} reviews)
Distance: ${dentist.distance}
Accepted insurance: ${dentist.insurance.join(", ")}
Dental.com Network provider: ${dentist.networkProvider ? "yes" : "no"}
Directions: https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(dentist.address)}`
        }
      ],
      structuredContent: { dentist }
    };
  }
});

// src/lib/mcp/tools/list-insurance-carriers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_insurance_carriers_default = defineTool3({
  name: "list_insurance_carriers",
  title: "List insurance carriers",
  description: "List the dental insurance carriers findadentist supports, optionally with how many directory dentists accept each one.",
  inputSchema: {
    withCounts: z3.boolean().optional().describe("Include the number of dentists accepting each carrier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ withCounts }) => {
    const rows = insuranceCarriers.map((carrier) => ({
      carrier,
      dentistCount: dentists.filter((d) => d.insurance.includes(carrier)).length
    }));
    return {
      content: [
        {
          type: "text",
          text: rows.map((r) => withCounts ? `${r.carrier} \u2014 ${r.dentistCount} dentist(s)` : r.carrier).join("\n")
        }
      ],
      structuredContent: { carriers: rows }
    };
  }
});

// src/lib/mcp/tools/list-specialties.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_specialties_default = defineTool4({
  name: "list_specialties",
  title: "List dental specialties",
  description: "List the dental specialties findadentist covers and how many directory dentists offer each.",
  inputSchema: {
    query: z4.string().optional().describe("Optional text filter applied to specialty names.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const rows = specialties.filter((s) => !q || s.toLowerCase().includes(q)).map((specialty) => ({
      specialty,
      dentistCount: dentists.filter((d) => d.specialty === specialty).length
    }));
    return {
      content: [
        { type: "text", text: rows.map((r) => `${r.specialty} \u2014 ${r.dentistCount} dentist(s)`).join("\n") }
      ],
      structuredContent: { specialties: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "otuenikomkqbxdwoipet";
var mcp_default = defineMcp({
  name: "findadentist",
  title: "findadentist",
  version: "0.1.0",
  instructions: "Tools for findadentist, a dentist discovery app. Use `search_dentists` to find dentists by specialty, insurance, location text, or rating; `get_dentist` for a full profile; `list_insurance_carriers` and `list_specialties` to discover valid filter values.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_dentists_default, get_dentist_default, list_insurance_carriers_default, list_specialties_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
